FORMAT: 1A
HOST: http://frontend.park.mail.ru/api/

# Technopark frontend

Описание API проекта по курсу "Фронтенд" Технопарка Mail.Ru

## Авторизация [/session]

### Проверка авторизации пользователя [GET]

+ Response 200 (application/json)

        {
            "id": 1
        }
        
+ Response 401 (application/json)

        {}

### Логин пользователя [PUT]

+ Request (application/json)

        {
            "login": "dmitrydorofeev",
            "password": "veeforodyrtimd"
        }

+ Response 200 (application/json)

        {
            "id": 1
        }
        
        
+ Response 400 (application/json)

        {}

### Логаут [DELETE]

+ Response 200 (application/json)

        {}        

## Пользователи [/user]

### Создание пользователя [PUT]

+ Request (application/json)

        {
            "login": "dmitrydorofeev",
            "password": "veeforodyrtimd",
            "email": "me@dmitrydorofeev.ru"
        }
        
+ Response 200 (application/json)

        {
            "id": 7
        }
        
+ Response 403 (application/json)

        {}

## Конкретный юзер [/user/{id}]
+ Parameters
    + id (number) - ID пользователя
        
### Получение информации о пользователе [GET]

+ Response 200 (application/json)

        {
            "id": 7,
            "login": "dmitrydorofeev",
            "email": "me@dmitrydorofeev.ru"
        }


+ Response 401 (application/json)

        {}

### Редактирование пользователя [POST]

+ Request (application/json)

        {
            "login": "dmitrydorofeev",
            "password": "veeforodyrtimd",
            "email": "me@dmitrydorofeev.ru"
        }
        

+ Response 200 (application/json)

        {
            "id": "1"
        }
        
+ Response 403 (application/json)

        {
            "status": 403,
            "message": "Чужой юзер"
        }

### Удаление пользователя [DELETE]
        

+ Response 200 (application/json)

        {}
        
+ Response 403 (application/json)

        {
            "status": 403,
            "message": "Чужой юзер"
        }